### PR TITLE
upgrade deprecated libraries

### PR DESCRIPTION
**Pull request by butlerx**

### CODE REVIEW

**Comment by VoyTechnology** [comment]
Will approve once CI passes.
```
Error: Cannot find module './lib/_stream_readable.js'
```

Also, would upgrading to Node 6+ help with anything?

**Comment by butlerx** [comment]
ci is failing due too it ignoreing the circle version 2 file that issue is on master and seperate to this pr

and by 6+ do you mean node version 7 or 8, not currently though one the new lts comes out in oct/nov theres no harm upgrading then simply to track latest lts

**Comment by butlerx** [comment]
test failing not due to #212
